[metadata]
creation_date = "2020/08/14"
maturity = "production"
updated_date = "2020/11/03"

[rule]
author = ["Elastic"]
description = """
Identifies the use of the networksetup command to setup a local host webproxy. This may indicate an attempt to hijack
Web Browsers traffic for credentials access via Sniffing Web Traffic.
"""
from = "now-9m"
index = ["auditbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "Browser Hijack via Setting the Web Proxy to Localhost"
references = ["https://objectivebythesea.com/v2/talks/OBTS_v2_Zohar.pdf"]
risk_score = 73
rule_id = "10a500bb-a28f-418e-ba29-ca4c8d1a9f2f"
severity = "high"
tags = ["Elastic", "Host", "macOS", "Threat Detection", "Credential Access"]
type = "query"

query = '''
event.category:process and event.type:(start or process_started) and
 process.name:networksetup and process.args:(("-setwebproxy" or "-setsecurewebproxy") and (127.0.* or localhost or 0.0.0.0))
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1539"
name = "Steal Web Session Cookie"
reference = "https://attack.mitre.org/techniques/T1539/"


[rule.threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"

