[metadata]
creation_date = "2021/01/05"
maturity = "production"
updated_date = "2021/01/05"

[rule]
author = ["Elastic"]
description = """
Identifies the use of the networksetup built-in command to setup the webproxy settings. This may indicate an attempt to
hijack Web Browsers traffic for credentials access via Sniffing or redirection.
"""
false_positives = ["Legit WebProxy Settings Modification"]
from = "now-9m"
index = ["auditbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "WebProxy Settings Modification"
references = [
    "https://unit42.paloaltonetworks.com/mac-malware-steals-cryptocurrency-exchanges-cookies/",
    "https://objectivebythesea.com/v2/talks/OBTS_v2_Zohar.pdf",
]
risk_score = 73
rule_id = "10a500bb-a28f-418e-ba29-ca4c8d1a9f2f"
severity = "high"
tags = ["Elastic", "Host", "macOS", "Threat Detection", "Credential Access"]
type = "query"

query = '''
event.category:process and event.type:(start or process_started) and
 process.name:networksetup and process.args:("-setwebproxy" or "-setsecurewebproxy")
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1539"
name = "Steal Web Session Cookie"
reference = "https://attack.mitre.org/techniques/T1539/"


[rule.threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"

